#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the Firmware_Test_user.mk file instead.
#

# Constants automatically defined by the selected modules
Firmware_Test_DEBUG = 1

# Our target application
TRG += Firmware_Test

Firmware_Test_PREFIX = "arm-none-eabi-"

Firmware_Test_SUFFIX = ""

Firmware_Test_SRC_PATH = Firmware_Test

Firmware_Test_HW_PATH = Firmware_Test

# Files automatically generated by the wizard. DO NOT EDIT, USE Firmware_Test_USER_CSRC INSTEAD!
Firmware_Test_WIZARD_CSRC = \
	bertos/cpu/cortex-m3/hw/switch_ctx_cm3.c \
	bertos/mware/event.c \
	bertos/kern/sem.c \
	bertos/cpu/cortex-m3/drv/timer_cm3.c \
	bertos/struct/heap.c \
	bertos/drv/i2c_bitbang.c \
	bertos/io/kfile.c \
	bertos/kern/monitor.c \
	bertos/cpu/cortex-m3/drv/i2c_stm32.c \
	bertos/drv/timer.c \
	bertos/kern/signal.c \
	bertos/kern/proc.c \
	bertos/mware/formatwr.c \
	bertos/mware/hex.c \
	bertos/drv/i2c.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE Firmware_Test_USER_PCSRC INSTEAD!
Firmware_Test_WIZARD_PCSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE Firmware_Test_USER_CPPASRC INSTEAD!
Firmware_Test_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE Firmware_Test_USER_CXXSRC INSTEAD!
Firmware_Test_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE Firmware_Test_USER_ASRC INSTEAD!
Firmware_Test_WIZARD_ASRC = \
	 \
	#

Firmware_Test_CPPFLAGS = -D'CPU_FREQ=(72000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(Firmware_Test_HW_PATH) -I$(Firmware_Test_SRC_PATH) $(Firmware_Test_CPU_CPPFLAGS) $(Firmware_Test_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
Firmware_Test_LDFLAGS = $(Firmware_Test_CPU_LDFLAGS) $(Firmware_Test_WIZARD_LDFLAGS) $(Firmware_Test_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
Firmware_Test_CPPAFLAGS = $(Firmware_Test_CPU_CPPAFLAGS) $(Firmware_Test_WIZARD_CPPAFLAGS) $(Firmware_Test_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
Firmware_Test_CSRC = $(Firmware_Test_CPU_CSRC) $(Firmware_Test_WIZARD_CSRC) $(Firmware_Test_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
Firmware_Test_PCSRC = $(Firmware_Test_CPU_PCSRC) $(Firmware_Test_WIZARD_PCSRC) $(Firmware_Test_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
Firmware_Test_CPPASRC = $(Firmware_Test_CPU_CPPASRC) $(Firmware_Test_WIZARD_CPPASRC) $(Firmware_Test_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
Firmware_Test_CXXSRC = $(Firmware_Test_CPU_CXXSRC) $(Firmware_Test_WIZARD_CXXSRC) $(Firmware_Test_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
Firmware_Test_ASRC = $(Firmware_Test_CPU_ASRC) $(Firmware_Test_WIZARD_ASRC) $(Firmware_Test_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
Firmware_Test_CPU_CPPASRC = bertos/cpu/cortex-m3/hw/crt_cm3.S bertos/cpu/cortex-m3/hw/vectors_cm3.S 
Firmware_Test_CPU_CPPAFLAGS = -g -gdwarf-2 -mthumb -mno-thumb-interwork
Firmware_Test_CPU_CPPFLAGS = -O0 -g3 -gdwarf-2 -mthumb -mno-thumb-interwork -fno-strict-aliasing -fwrapv -fverbose-asm -Ibertos/cpu/cortex-m3/ -D__ARM_STM32F103RB__
Firmware_Test_CPU_CSRC = bertos/cpu/cortex-m3/hw/init_cm3.c bertos/cpu/cortex-m3/drv/irq_cm3.c bertos/cpu/cortex-m3/drv/gpio_stm32.c bertos/cpu/cortex-m3/drv/clock_stm32.c 
Firmware_Test_PROGRAMMER_CPU = stm32
Firmware_Test_CPU_LDFLAGS = -mthumb -mno-thumb-interwork -nostartfiles -Wl,--no-warn-mismatch -Wl,-dT bertos/cpu/cortex-m3/scripts/stm32f103rb_rom.ld
Firmware_Test_STOPFLASH_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
Firmware_Test_CPU = cortex-m3
Firmware_Test_STOPDEBUG_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
Firmware_Test_DEBUG_SCRIPT = bertos/prg_scripts/arm/debug.sh
Firmware_Test_FLASH_SCRIPT = bertos/prg_scripts/arm/flash-stm32.sh

include $(Firmware_Test_SRC_PATH)/Firmware_Test_user.mk
