#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the sensor_actuator_user.mk file instead.
#

# Constants automatically defined by the selected modules
sensor_actuator_DEBUG = 1

# Our target application
TRG += sensor_actuator

sensor_actuator_PREFIX = "/home/olivier/opt/arm/bin/arm-none-eabi-"

sensor_actuator_SUFFIX = ""

sensor_actuator_SRC_PATH = sensor_actuator

sensor_actuator_HW_PATH = sensor_actuator

# Files automatically generated by the wizard. DO NOT EDIT, USE sensor_actuator_USER_CSRC INSTEAD!
sensor_actuator_WIZARD_CSRC = \
	bertos/cpu/cortex-m3/drv/i2c_stm32.c \
	bertos/cpu/cortex-m3/drv/can_stm32.c \
	bertos/cpu/cortex-m3/hw/switch_ctx_cm3.c \
	bertos/kern/signal.c \
	bertos/kern/monitor.c \
	bertos/cpu/cortex-m3/drv/timer_cm3.c \
	bertos/drv/i2c_bitbang.c \
	bertos/cpu/cortex-m3/drv/adc_stm32.c \
	bertos/mware/formatwr.c \
	bertos/drv/can.c \
	bertos/drv/adc.c \
	bertos/drv/timer.c \
	bertos/mware/event.c \
	bertos/kern/proc.c \
	bertos/mware/hex.c \
	bertos/drv/i2c.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE sensor_actuator_USER_PCSRC INSTEAD!
sensor_actuator_WIZARD_PCSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE sensor_actuator_USER_CPPASRC INSTEAD!
sensor_actuator_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE sensor_actuator_USER_CXXSRC INSTEAD!
sensor_actuator_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE sensor_actuator_USER_ASRC INSTEAD!
sensor_actuator_WIZARD_ASRC = \
	 \
	#

sensor_actuator_CPPFLAGS = -D'CPU_FREQ=(72000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(sensor_actuator_HW_PATH) -I$(sensor_actuator_SRC_PATH) $(sensor_actuator_CPU_CPPFLAGS) $(sensor_actuator_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
sensor_actuator_LDFLAGS = $(sensor_actuator_CPU_LDFLAGS) $(sensor_actuator_WIZARD_LDFLAGS) $(sensor_actuator_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
sensor_actuator_CPPAFLAGS = $(sensor_actuator_CPU_CPPAFLAGS) $(sensor_actuator_WIZARD_CPPAFLAGS) $(sensor_actuator_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
sensor_actuator_CSRC = $(sensor_actuator_CPU_CSRC) $(sensor_actuator_WIZARD_CSRC) $(sensor_actuator_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
sensor_actuator_PCSRC = $(sensor_actuator_CPU_PCSRC) $(sensor_actuator_WIZARD_PCSRC) $(sensor_actuator_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
sensor_actuator_CPPASRC = $(sensor_actuator_CPU_CPPASRC) $(sensor_actuator_WIZARD_CPPASRC) $(sensor_actuator_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
sensor_actuator_CXXSRC = $(sensor_actuator_CPU_CXXSRC) $(sensor_actuator_WIZARD_CXXSRC) $(sensor_actuator_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
sensor_actuator_ASRC = $(sensor_actuator_CPU_ASRC) $(sensor_actuator_WIZARD_ASRC) $(sensor_actuator_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
sensor_actuator_CPU_CPPASRC = bertos/cpu/cortex-m3/hw/crt_cm3.S bertos/cpu/cortex-m3/hw/vectors_cm3.S 
sensor_actuator_CPU_CPPAFLAGS = -g -gdwarf-2 -mthumb -mno-thumb-interwork
sensor_actuator_CPU_CPPFLAGS = -O0 -g3 -gdwarf-2 -mthumb -mno-thumb-interwork -fno-strict-aliasing -fwrapv -fverbose-asm -Ibertos/cpu/cortex-m3/ -D__ARM_STM32F103RB__
sensor_actuator_CPU_CSRC = bertos/cpu/cortex-m3/hw/init_cm3.c bertos/cpu/cortex-m3/drv/irq_cm3.c bertos/cpu/cortex-m3/drv/gpio_stm32.c bertos/cpu/cortex-m3/drv/clock_stm32.c 
sensor_actuator_PROGRAMMER_CPU = stm32
sensor_actuator_CPU_LDFLAGS = -mthumb -mno-thumb-interwork -nostartfiles -Wl,--no-warn-mismatch -Wl,-dT bertos/cpu/cortex-m3/scripts/stm32f103rb_rom.ld
sensor_actuator_STOPFLASH_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
sensor_actuator_CPU = cortex-m3
sensor_actuator_STOPDEBUG_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
sensor_actuator_DEBUG_SCRIPT = bertos/prg_scripts/arm/debug.sh
sensor_actuator_FLASH_SCRIPT = bertos/prg_scripts/arm/flash-stm32.sh

include $(sensor_actuator_SRC_PATH)/sensor_actuator_user.mk
