#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the test_ax12_user.mk file instead.
#

# Constants automatically defined by the selected modules
test_ax12_DEBUG = 1

# Our target application
TRG += test_ax12

test_ax12_PREFIX = "/home/nicolasd/opt/arm/bin/arm-none-eabi-"

test_ax12_SUFFIX = ""

test_ax12_SRC_PATH = test_ax12

test_ax12_HW_PATH = test_ax12

# Files automatically generated by the wizard. DO NOT EDIT, USE test_ax12_USER_CSRC INSTEAD!
test_ax12_WIZARD_CSRC = \
	bertos/cpu/cortex-m3/drv/timer_cm3.c \
	bertos/cpu/cortex-m3/hw/switch_ctx_cm3.c \
	bertos/drv/timer.c \
	bertos/io/kfile.c \
	bertos/kern/monitor.c \
	bertos/kern/proc.c \
	bertos/kern/sem.c \
	bertos/kern/signal.c \
	bertos/mware/event.c \
	bertos/mware/formatwr.c \
	bertos/mware/hex.c \
	bertos/struct/heap.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE test_ax12_USER_PCSRC INSTEAD!
test_ax12_WIZARD_PCSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE test_ax12_USER_CPPASRC INSTEAD!
test_ax12_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE test_ax12_USER_CXXSRC INSTEAD!
test_ax12_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE test_ax12_USER_ASRC INSTEAD!
test_ax12_WIZARD_ASRC = \
	 \
	#

test_ax12_CPPFLAGS = -D'CPU_FREQ=(72000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(test_ax12_HW_PATH) -I$(test_ax12_SRC_PATH) $(test_ax12_CPU_CPPFLAGS) $(test_ax12_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
test_ax12_LDFLAGS = $(test_ax12_CPU_LDFLAGS) $(test_ax12_WIZARD_LDFLAGS) $(test_ax12_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
test_ax12_CPPAFLAGS = $(test_ax12_CPU_CPPAFLAGS) $(test_ax12_WIZARD_CPPAFLAGS) $(test_ax12_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
test_ax12_CSRC = $(test_ax12_CPU_CSRC) $(test_ax12_WIZARD_CSRC) $(test_ax12_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
test_ax12_PCSRC = $(test_ax12_CPU_PCSRC) $(test_ax12_WIZARD_PCSRC) $(test_ax12_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
test_ax12_CPPASRC = $(test_ax12_CPU_CPPASRC) $(test_ax12_WIZARD_CPPASRC) $(test_ax12_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
test_ax12_CXXSRC = $(test_ax12_CPU_CXXSRC) $(test_ax12_WIZARD_CXXSRC) $(test_ax12_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
test_ax12_ASRC = $(test_ax12_CPU_ASRC) $(test_ax12_WIZARD_ASRC) $(test_ax12_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
test_ax12_CPU_CPPASRC = bertos/cpu/cortex-m3/hw/crt_cm3.S bertos/cpu/cortex-m3/hw/vectors_cm3.S 
test_ax12_CPU_CPPAFLAGS = -g -gdwarf-2 -mthumb -mno-thumb-interwork
test_ax12_CPU_CPPFLAGS = -O0 -g3 -gdwarf-2 -mthumb -mno-thumb-interwork -fno-strict-aliasing -fwrapv -fverbose-asm -Ibertos/cpu/cortex-m3/ -D__ARM_STM32F103RB__
test_ax12_CPU_CSRC = bertos/cpu/cortex-m3/hw/init_cm3.c bertos/cpu/cortex-m3/drv/irq_cm3.c bertos/cpu/cortex-m3/drv/gpio_stm32.c bertos/cpu/cortex-m3/drv/clock_stm32.c 
test_ax12_PROGRAMMER_CPU = stm32
test_ax12_CPU_LDFLAGS = -mthumb -mno-thumb-interwork -nostartfiles -Wl,--no-warn-mismatch -Wl,-dT bertos/cpu/cortex-m3/scripts/stm32f103rb_rom.ld
test_ax12_STOPFLASH_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
test_ax12_CPU = cortex-m3
test_ax12_STOPDEBUG_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
test_ax12_DEBUG_SCRIPT = bertos/prg_scripts/arm/debug.sh
test_ax12_FLASH_SCRIPT = bertos/prg_scripts/arm/flash-stm32.sh

include $(test_ax12_SRC_PATH)/test_ax12_user.mk
