PROJNAME=teleUScms
DEVICE=CY8C29466
BASEDEVICE=CY8C29000
PROJPATH=C:/DOCUME~1/XL/MYDOCU~1/PSOCDE~1.0PR/TELEUS~1/TELEUS~1/TELEUS~1
PSOCDIR=C:/PROGRA~1/Cypress/Common/CYPRES~3
INCLUDE_PATH=C:/PROGRA~1/Cypress/Common/CYPRES~3/tools/include/CY8C29~1
CSRCS= main.c
LIBCSRCS=
ASMSRCS= delay.asm
LIBASMSRCS= bufcomp.asm bufcompint.asm comp.asm compteur.asm compteurint.asm declencheur.asm declencheurint.asm filtre1.asm filtre2.asm i2chwcommon.asm i2chwint.asm i2chwrsrcinits.asm inverseur.asm inverseurint.asm pga_1.asm pga_2.asm pga_3.asm porteuse.asm porteuseint.asm psocconfig.asm psocconfigtbl.asm tempsmort.asm tempsmortint.asm
OBJECT_SOURCES= delay.asm main.c
FILLVALUE=0x30
LASTROM=0x7fff
LASTRAM=0x7ff
LAST_DATARAM=0x6ff
CODECOMPRESSOR=
MORE_CFLAGS=-Wf-Osize -Wf-LMM8 -D_LMM
RELSTART=0x1a0
CDEFINES=
LIBS=
UMLIBS=
LIB_PATH=
ENABLE_ALIGN_SHIFT=0
LMM=1
SYS_INC_CONTENTS:=SYSTEM_STACK_PAGE:_equ_7 SYSTEM_STACK_BASE_ADDR:_equ_0h SYSTEM_LARGE_MEMORY_MODEL:_equ_1 SYSTEM_SMALL_MEMORY_MODEL:_equ_0 IMAGECRAFT:_equ_1 HITECH:_equ_2 TOOLCHAIN:_equ_IMAGECRAFT 
SYSTEM_TOOLS=1
CSFLOW=
CONFIG_NAMES=teleuscms 
