//*****************************************************************************
//*****************************************************************************
//  FILENAME: bufComp.h
//  Version: 1.3, Updated on 2009/10/15 at 17:11:37
//  Generated by PSoC Designer 5.0.1127.0
//
//  DESCRIPTION: DigitalBuffers User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>

#pragma fastcall16 bufComp_EnableInt
#pragma fastcall16 bufComp_DisableInt
#pragma fastcall16 bufComp_Start
#pragma fastcall16 bufComp_Stop

//-------------------------------------------------
// Prototypes of the bufComp API.
//-------------------------------------------------

extern void bufComp_EnableInt(void);
extern void bufComp_DisableInt(void);
extern void bufComp_Start(void);
extern void bufComp_Stop(void);


//--------------------------------------------------
// Constants for bufComp API's.
//--------------------------------------------------
#define bufComp_CONTROL_REG_START_BIT          ( 0x01 )
#define bufComp_INT_REG_ADDR                   ( 0x0df )
#define bufComp_INT_MASK                       ( 0x08 )


//--------------------------------------------------
// Constants for bufComp user defined values
//--------------------------------------------------
#pragma ioport  bufComp_DATA_0_REG: 0x04c                  //DR0 Count register
BYTE            bufComp_DATA_0_REG;
#pragma ioport  bufComp_DATA_1_REG: 0x04d                  //DR1 Period register
BYTE            bufComp_DATA_1_REG;
#pragma ioport  bufComp_DATA_2_REG: 0x04e                  //DR2 Compare register
BYTE            bufComp_DATA_2_REG;
#pragma ioport  bufComp_CONTROL_REG:    0x04f              //Control register
BYTE            bufComp_CONTROL_REG;
#pragma ioport  bufComp_FUNC_REG:   0x14c                  //Function register
BYTE            bufComp_FUNC_REG;
#pragma ioport  bufComp_INPUT_REG:  0x14d                  //Input register
BYTE            bufComp_INPUT_REG;
#pragma ioport  bufComp_OUTPUT_REG: 0x14e                  //Output register
BYTE            bufComp_OUTPUT_REG;
#pragma ioport  bufComp_INT_REG:       0x0df               //Interrupt Mask Register
BYTE            bufComp_INT_REG;


//-------------------------------------------------
// Register Addresses for bufComp
//-------------------------------------------------


//-------------------------------------------------
// bufComp Macro 'Functions'
//-------------------------------------------------

#define bufComp_Start_M \
   bufComp_CONTROL_REG |=  bufComp_CONTROL_REG_START_BIT

#define bufComp_Stop_M  \
   bufComp_CONTROL_REG &= ~bufComp_CONTROL_REG_START_BIT

#define bufComp_EnableInt_M   \
   M8C_EnableIntMask(bufComp_INT_REG, bufComp_INT_MASK)

#define bufComp_DisableInt_M  \
   M8C_DisableIntMask(bufComp_INT_REG, bufComp_INT_MASK)

// end of file bufComp.h
