//*****************************************************************************
//*****************************************************************************
//  FILENAME:  comp.h
//  Version: 3.3, Updated on 2009/10/9 at 10:6:29
//  Generated by PSoC Designer 5.0.1127.0
//
//  DESCRIPTION:  CMPPRG User Module C Language interface file.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <M8C.h>

//-------------------------------------------------
// Defines for comp API's.
//-------------------------------------------------
#define comp_OFF         0
#define comp_LOWPOWER    1
#define comp_MEDPOWER    2
#define comp_HIGHPOWER   3

#define comp_REF1_000   0xf0
#define comp_REF0_937   0xe0
#define comp_REF0_875   0xd0
#define comp_REF0_812   0xc0
#define comp_REF0_750   0xb0
#define comp_REF0_688   0xa0
#define comp_REF0_625   0x90
#define comp_REF0_562   0x80
#define comp_REF0_500   0x70
#define comp_REF0_437   0x60
#define comp_REF0_375   0x50
#define comp_REF0_312   0x40
#define comp_REF0_250   0x30
#define comp_REF0_188   0x20
#define comp_REF0_125   0x10
#define comp_REF0_062   0x00
#define comp_REF0_042   0x14
#define comp_REF0_021   0x04


#pragma fastcall16 comp_Start             // Proxy class 2
#pragma fastcall16 comp_SetPower          // Proxy class 2
#pragma fastcall16 comp_SetRef            // Proxy class 2
#pragma fastcall16 comp_Stop              // Proxy class 1

//-------------------------------------------------
// Prototypes of the comp API.
//-------------------------------------------------
extern void comp_Start(BYTE bPowerSetting);
extern void comp_SetPower(BYTE bPowerSetting);
extern void comp_SetRef(BYTE bRefValue);
extern void comp_Stop(void);

//-------------------------------------------------
// Hardware Register Definitions
//-------------------------------------------------
#pragma ioport  comp_COMP_CR0:  0x07d
BYTE            comp_COMP_CR0;
#pragma ioport  comp_COMP_CR1:  0x07e
BYTE            comp_COMP_CR1;
#pragma ioport  comp_COMP_CR2:  0x07f
BYTE            comp_COMP_CR2;
#pragma ioport  comp_COMP_CR3:  0x07c
BYTE            comp_COMP_CR3;

// end of file comp.h
