;;*****************************************************************************
;;*****************************************************************************
;;  FILENAME: compteurINT.asm
;;  Version: 1.1, Updated on 2009/10/15 at 17:11:37
;;  Generated by PSoC Designer 5.0.1127.0
;;
;;  DESCRIPTION: TachTimer16 Interrupt Service Routine
;;-----------------------------------------------------------------------------
;;  Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
;;*****************************************************************************
;;*****************************************************************************

include "m8c.inc"
include "compteur.inc"

;-----------------------------------------------
;  Global Symbols
;-----------------------------------------------
export  _compteur_MSB_ISR
export  _compteur_LSB_ISR


AREA bss (RAM,REL)

;@PSoC_UserCode_INIT@ (Do not change this line.)
;---------------------------------------------------
; Insert your custom declarations below this banner
;---------------------------------------------------

;------------------------
;  Constant Definitions
;------------------------


;------------------------
; Variable Allocation
;------------------------


;---------------------------------------------------
; Insert your custom declarations above this banner
;---------------------------------------------------
;@PSoC_UserCode_END@ (Do not change this line.)


AREA UserModules (ROM, REL)

;-----------------------------------------------------------------------------
;  FUNCTION NAME: _compteur_ISR
;
;  DESCRIPTION: Unless modified, this implements only a null handler stub.
;  Handles the terminal count event
;
;-----------------------------------------------------------------------------
;
_compteur_MSB_ISR:

   ;@PSoC_UserCode_BODY_MSB@ (Do not change this line.)
   ;---------------------------------------------------
   ; Insert your custom code below this banner
   ;---------------------------------------------------
   ;   NOTE: interrupt service routines must preserve
   ;   the values of the A and X CPU registers.
   ljmp _compteurFin_int
   ;---------------------------------------------------
   ; Insert your custom code above this banner
   ;---------------------------------------------------
   ;@PSoC_UserCode_END@ (Do not change this line.)

   reti
;-----------------------------------------------------------------------------
;  FUNCTION NAME: _compteur_LSB_ISR
;
;  DESCRIPTION: Unless modified, this implements only a null handler stub.
;  Handles the capture event
;
;-----------------------------------------------------------------------------
;
_compteur_LSB_ISR:

   ;@PSoC_UserCode_BODY_LSB@ (Do not change this line.)

   ;---------------------------------------------------
   ; Insert your custom code below this banner
   ;---------------------------------------------------
   ;   NOTE: interrupt service routines must preserve
   ;   the values of the A and X CPU registers.
   ljmp _compteurCapture_int
   ;---------------------------------------------------
   ; Insert your custom code above this banner
   ;---------------------------------------------------
   ;@PSoC_UserCode_END@ (Do not change this line.)

   reti

; end of file compteurINT.asm
