//*****************************************************************************
//*****************************************************************************
//  FILENAME: filtre2.h
//   Version: 5.5, Updated on 2009/10/9 at 10:6:29
//  Generated by PSoC Designer 5.0.1127.0
//
//  DESCRIPTION: C declarations for the BPF2 User Module.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>

#pragma fastcall16 filtre2_Start
#pragma fastcall16 filtre2_SetPower
#pragma fastcall16 filtre2_Stop
#pragma fastcall16 filtre2_SetC1
#pragma fastcall16 filtre2_SetC2
#pragma fastcall16 filtre2_SetC3
#pragma fastcall16 filtre2_SetC4
#pragma fastcall16 filtre2_SetCA
#pragma fastcall16 filtre2_SetCB
#pragma fastcall16 filtre2_SetPolarity


//-------------------------------------------------
// Prototypes of the filtre2 API.
//-------------------------------------------------

extern void filtre2_Start(BYTE bPowerSetting);
extern void filtre2_SetPower(BYTE bPowerSetting);
extern void filtre2_Stop(void);
extern void filtre2_SetC1(BYTE bCapValue);
extern void filtre2_SetC2(BYTE bCapValue);
extern void filtre2_SetC3(BYTE bCapValue);
extern void filtre2_SetC4(BYTE bCapValue);
extern void filtre2_SetCA(BYTE bCapValue);
extern void filtre2_SetCB(BYTE bCapValue);
extern void filtre2_SetPolarity(BYTE bPolaritySetting);


//-------------------------------------------------
// Defines for filtre2 API's.
//-------------------------------------------------

#define filtre2_OFF                              (0x00)
#define filtre2_LOWPOWER                         (0x01)
#define filtre2_MEDPOWER                         (0x02)
#define filtre2_HIGHPOWER                        (0x03)

#define filtre2_FEEDBACK_16                      (0x00)
#define filtre2_FEEDBACK_32                      (0x01)

#define filtre2_POLARITY_INVERTING               (0x00)
#define filtre2_POLARITY_NON_INVERTING           (0x01)

//-------------------------------------------------
// Hardware Register Definitions
//-------------------------------------------------

#pragma ioport  filtre2_FLIN_CR0:   0x088                       //Analog SCA control register 0
BYTE            filtre2_FLIN_CR0;
#pragma ioport  filtre2_FLIN_CR1:   0x089                       //Analog SCA control register 1
BYTE            filtre2_FLIN_CR1;
#pragma ioport  filtre2_FLIN_CR2:   0x08a                       //Analog SCA control register 2
BYTE            filtre2_FLIN_CR2;
#pragma ioport  filtre2_FLIN_CR3:   0x08b                       //Analog SCA control register 3
BYTE            filtre2_FLIN_CR3;
#pragma ioport  filtre2_FLFB_CR0:   0x098                       //Analog SCB control register 0
BYTE            filtre2_FLFB_CR0;
#pragma ioport  filtre2_FLFB_CR1:   0x099                       //Analog SCB control register 1
BYTE            filtre2_FLFB_CR1;
#pragma ioport  filtre2_FLFB_CR2:   0x09a                       //Analog SCB control register 2
BYTE            filtre2_FLFB_CR2;
#pragma ioport  filtre2_FLFB_CR3:   0x09b                       //Analog SCB control register 3
BYTE            filtre2_FLFB_CR3;

//  filtre2 Cap naming convention per Gregorian and Temes, p293

#pragma ioport  filtre2_FILT_C1_REG:    0x088
BYTE            filtre2_FILT_C1_REG;
#pragma ioport  filtre2_FILT_C2_REG:    0x089
BYTE            filtre2_FILT_C2_REG;
#pragma ioport  filtre2_FILT_C3_REG:    0x098
BYTE            filtre2_FILT_C3_REG;
#pragma ioport  filtre2_FILT_C4_REG:    0x08a
BYTE            filtre2_FILT_C4_REG;
#pragma ioport  filtre2_FILT_CA_REG:    0x088
BYTE            filtre2_FILT_CA_REG;
#pragma ioport  filtre2_FILT_CB_REG:    0x098
BYTE            filtre2_FILT_CB_REG;


// end of file filtre2.h
