/******************************************************************************
*  Generated by PSoC Designer 5.0.1127.0
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "I2CHWCommon.h"
#include "I2CHWSlave.h"
#include "PGA_1.h"
#include "PGA_2.h"
#include "PGA_3.h"
#include "bufComp.h"
#include "comp.h"
#include "compteur.h"
#include "declencheur.h"
#include "filtre1.h"
#include "filtre2.h"
#include "inverseur.h"
#include "porteuse.h"
#include "tempsMort.h"

#endif
